Switch to single bevy dep with no default features (#33)
Impossible to use a patched bevy 0.5 version alongside a dep that
depends on bevy sub crates (bevy_ecs, bevy_app, etc).

Doing so gives: error[E0277]: the trait bound `NetworkingPlugin: bevy::prelude::Plugin` is not satisfied

See: https://github.com/bevyengine/bevy/blob/main/docs/plugins_guidelines.md#bevy-features

Guidelines from bevy now to use `bevy` without default features in this
case.

Discord link to start of conversation:
https://discord.com/channels/691052431525675048/691052431974465548/860423772979593246